services:
  # 1. Product API
  - type: web
    name: eshoppingzone-product
    runtime: docker
    dockerContext: EShoppingZone.Product.API
    dockerfilePath: EShoppingZone.Product.API/Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_gcServer
        value: "0"
      - key: DOTNET_PRINT_TELEMETRY_MESSAGE
        value: "false"
      - key: COMPlus_ThreadPool_ForceMaxWorkerThreads
        value: "20"
      - key: COMPlus_ThreadPool_ForceMaxIOThreads
        value: "20"
      - key: ConnectionStrings__ProductDb
        value: Host=${eshoppingzone-db.host};Port=${eshoppingzone-db.port};Database=${eshoppingzone-db.database};Username=${eshoppingzone-db.user};Password=${eshoppingzone-db.password};SSL Mode=Require;Trust Server Certificate=true
      - key: Jwt__Key
        value: EShoppingZone_SuperSecretKey_2026_DoNotShare_MinLength32Chars!
      - key: Jwt__Issuer
        value: EShoppingZone
      - key: Jwt__Audience
        value: EShoppingZoneClients

  # 2. Profile API
  - type: web
    name: eshoppingzone-profile
    runtime: docker
    dockerContext: EShoppingZone.Profile.API
    dockerfilePath: EShoppingZone.Profile.API/Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_gcServer
        value: "0"
      - key: DOTNET_PRINT_TELEMETRY_MESSAGE
        value: "false"
      - key: COMPlus_ThreadPool_ForceMaxWorkerThreads
        value: "20"
      - key: COMPlus_ThreadPool_ForceMaxIOThreads
        value: "20"
      - key: ConnectionStrings__ProfileDb
        value: Host=${eshoppingzone-db.host};Port=${eshoppingzone-db.port};Database=${eshoppingzone-db.database};Username=${eshoppingzone-db.user};Password=${eshoppingzone-db.password};SSL Mode=Require;Trust Server Certificate=true
      - key: Jwt__Key
        value: EShoppingZone_SuperSecretKey_2026_DoNotShare_MinLength32Chars!
      - key: Jwt__Issuer
        value: EShoppingZone
      - key: Jwt__Audience
        value: EShoppingZoneClients

  # 3. Cart API
  - type: web
    name: eshoppingzone-cart
    runtime: docker
    dockerContext: EShoppingZone.Cart.API
    dockerfilePath: EShoppingZone.Cart.API/Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_gcServer
        value: "0"
      - key: DOTNET_PRINT_TELEMETRY_MESSAGE
        value: "false"
      - key: COMPlus_ThreadPool_ForceMaxWorkerThreads
        value: "20"
      - key: COMPlus_ThreadPool_ForceMaxIOThreads
        value: "20"
      - key: ConnectionStrings__CartDb
        value: Host=${eshoppingzone-db.host};Port=${eshoppingzone-db.port};Database=${eshoppingzone-db.database};Username=${eshoppingzone-db.user};Password=${eshoppingzone-db.password};SSL Mode=Require;Trust Server Certificate=true
      - key: Jwt__Key
        value: EShoppingZone_SuperSecretKey_2026_DoNotShare_MinLength32Chars!
      - key: Jwt__Issuer
        value: EShoppingZone
      - key: Jwt__Audience
        value: EShoppingZoneClients

  # 4. Order API
  - type: web
    name: eshoppingzone-order
    runtime: docker
    dockerContext: EShoppingZone.Order.API
    dockerfilePath: EShoppingZone.Order.API/Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_gcServer
        value: "0"
      - key: DOTNET_PRINT_TELEMETRY_MESSAGE
        value: "false"
      - key: COMPlus_ThreadPool_ForceMaxWorkerThreads
        value: "20"
      - key: COMPlus_ThreadPool_ForceMaxIOThreads
        value: "20"
      - key: ConnectionStrings__OrderDb
        value: Host=${eshoppingzone-db.host};Port=${eshoppingzone-db.port};Database=${eshoppingzone-db.database};Username=${eshoppingzone-db.user};Password=${eshoppingzone-db.password};SSL Mode=Require;Trust Server Certificate=true
      - key: Jwt__Key
        value: EShoppingZone_SuperSecretKey_2026_DoNotShare_MinLength32Chars!
      - key: Jwt__Issuer
        value: EShoppingZone
      - key: Jwt__Audience
        value: EShoppingZoneClients

  # 5. Wallet API
  - type: web
    name: eshoppingzone-wallet
    runtime: docker
    dockerContext: EShoppingZone.Wallet.API
    dockerfilePath: EShoppingZone.Wallet.API/Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_gcServer
        value: "0"
      - key: DOTNET_PRINT_TELEMETRY_MESSAGE
        value: "false"
      - key: COMPlus_ThreadPool_ForceMaxWorkerThreads
        value: "20"
      - key: COMPlus_ThreadPool_ForceMaxIOThreads
        value: "20"
      - key: ConnectionStrings__WalletDb
        value: Host=${eshoppingzone-db.host};Port=${eshoppingzone-db.port};Database=${eshoppingzone-db.database};Username=${eshoppingzone-db.user};Password=${eshoppingzone-db.password};SSL Mode=Require;Trust Server Certificate=true
      - key: Jwt__Key
        value: EShoppingZone_SuperSecretKey_2026_DoNotShare_MinLength32Chars!
      - key: Jwt__Issuer
        value: EShoppingZone
      - key: Jwt__Audience
        value: EShoppingZoneClients

databases:
  - name: eshoppingzone-db
    plan: free
